name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
<<<<<<< HEAD
        issue-message: 'Thank you for generating an issue to this project! Please wait while we get back to you.'' first issue'
        pr-message: 'We love Pull Requests! Thank you for contributing, however you will have to wait we check with your PR. '' first pr'
=======
        issue-message: 'Message that will be displayed on users'' first issue'
        pr-message: 'Message that will be displayed on users'' first pr'
>>>>>>> 816eab6f5119963d54c33577c4d1c6ea7165ed64
